### ISSUE TITLE
Modhub validation feedback: warning message missing on client side with separate farm

### ISSUE THREAD

**Issue by yumi-modding** [yumi-modding/FS22_CombineXP#11]
**Describe the bug**
The warning messages like "Crop Moisture" are missing on client side with separate farm
Need to reproduce on MP. To check if issue is present only on Dedi server

**To Reproduce**
Details to reproduce the behavior:
- Harvested crop: any
- Combine and cutter: any
- Yield: any
- Seasons mod activated? n/a
- Time of the day when harvesting: 7am to have moisture warning msg

**Screenshots**

**Additional context**

**Comment by jason0611** [comment]
Do you have access to a Dedi server? If not I could verify it for you.

**Comment by yumi-modding** [comment]
hello @jason0611 
Thanks, that would be great because I don't have access for now. I guess I will need to rent one soon to ease mod testing.
If you reproduce the bug, please let me know, and I will push a fix I've started to build so you can test correction is OK also.

**Comment by jason0611** [comment]
Ok, I will verify it this evening after work and give feedback after that.

**Comment by jason0611** [comment]
I've made two tests now: One in SP and one in MP on Dedi, both were the same save game which I transferred to the server. Version was the actual version from GitHub (24.01.2022).
SP: Threshing at 15:30 while it's raining in realistic mode. Speed drops and keeps between 3km/h and 5hm/h, moisture warning appears often.
MP: Threshing at 15:30 while it's raining in realistic mode. Speed drops and keeps between 3km/h and 5km/h, no moisture shows up, regardless of effective threshing speed.
I've chosen 15:30 because it just starts raining then. :-)

**Comment by yumi-modding** [comment]
Thanks a lot for your test, that very helpful. I can send you in a few minutes a zip with the code that should fix the issue so you can tell me if it's ok.
Can I use your github email address or do you prefer another way ?

**Comment by jason0611** [comment]
You may use the github address or martin@eller-essen.de. Both are equal. :-)

**Comment by yumi-modding** [comment]
Perfect, i deleted your answer to avoid robots scanning your email

**Comment by jason0611** [comment]
Thank you.
