### ISSUE TITLE
[Enhancement] Add semi Realistic mode (No moisture)

### ISSUE THREAD

**Issue by talianagisan** [yumi-modding/FS22_CombineXP#12]
The moisture is buggy, it's annoying as its artificial and just... It makes it a pain to harvest as I keep running out of time. Can we have a realistic option with it disabled?

**Comment by yumi-modding** [comment]
Hello,
The moisture management was clearly better on FS19 with Seasons mod computing a better value.
Unfortunately, this is not available on FS22, so I revert back to using time of the day to prevent harvesting wheat af full speed at 6am (something that seems to me impossible, where I live at least).
If you don't want that, you can edit combineXP.xml file that is in your modsSetting directory (next to mods dir) and change the values in the timeDependantSpeed section.
Default is like this. (Please note that if you set isActive="false", it would be overwritten by setting realistic mode in game panel.
 ```
   <timeDependantSpeed isActive="true">
        <cereal>
            <key value="9" time="0"/>
            <key value="8" time="2"/>
            <key value="6" time="4"/>
            <key value="2" time="6"/>
            <key value="2" time="8"/>
            <key value="4" time="10"/>
            <key value="9" time="12"/>
            <key value="10" time="14"/>
            <key value="10" time="16"/>
            <key value="10" time="18"/>
            <key value="10" time="20"/>
            <key value="9" time="22"/>
            <key value="9" time="24"/>
        </cereal>
```
So best option is to set the value (10 means 100% speed, 2 means 20%) you want for each time (8 -> 8am,... 18 -> 6pm...)
This example would for example set no constraint
 ```
   <timeDependantSpeed isActive="true">
        <cereal>
            <key value="10" time="0"/>
            <key value="10" time="2"/>
            <key value="10" time="4"/>
            <key value="10" time="6"/>
            <key value="10" time="8"/>
            <key value="10" time="10"/>
            <key value="10" time="12"/>
            <key value="10" time="14"/>
            <key value="10" time="16"/>
            <key value="10" time="18"/>
            <key value="10" time="20"/>
            <key value="10" time="22"/>
            <key value="10" time="24"/>
        </cereal>
```
By the way, if you have ideas to improve this, please let me know since I think there is something to do here.

**Comment by talianagisan** [comment]
I actually have the issue of it triggers all the time no matter what in my experience. It can be 4pm and I still get a massive kick to slowdown. I never looked too closely at the times till now. I also get 20-30fps drop at 105-120% combine power usage if not more. It was when I was doing beet harvesting, it could of been a REA issue as the way you slow down vehicles is not by increasing engine load but someother way.

Never really thought about it till now. Also it just sucks doing 1-2mph instead 3-4 due to moisture. 

You could likely calculate moisture by setting a baseline minimum/etc and having rain increase that per hour it rains, when it stops raining it dries based on wind or temp. The game SHOULD have values for that you can access due to the weather display showing them and the wind turbines run off windspeed calculations.

**Comment by talianagisan** [comment]
I can say that 80-90% of the time turning off crop moisture does nothing via xml based off more harvests so... yeah i think we need it as a seperate toggle as the setting version ingame works fine.

**Comment by miracleman51** [comment]
Hiya,

Loving the mod, although I also have the issue with crop moisture being high all of the time.  Im wondering of its mainly an issue for modded combines rather than vanilla ones, but Ive yet to test that theory out,

**Comment by yumi-modding** [comment]
I think there is a mistake in the display of the msg that i fixed but not pushed on GitHub. I'm working on the mod today to try to fix MP issue but i should first push this correction so you guys can at least check this is fixed.

**Comment by yumi-modding** [comment]
Fixed by last commit. Daytime limit (to simulate moisture) can now be set independently in the settings
