### ISSUE TITLE
combineXP.xml

### ISSUE THREAD

**Issue by DuckinBoots** [yumi-modding/FS22_CombineXP#14]
Hello! I have question about adding mod combine. I add link to xml : 
"vehicle xmlPath="$moddir$FS22_RSM_161/161.xml" basePerf="620"/" , but script don't see it or s.e.

So, what i doing wrong?
![fsScreen_2022_05_27_20_04_26](https://user-images.githubusercontent.com/54028622/170753208-2275a555-4b9b-4647-aa0c-3c4aba2fc586.png)

**Comment by yumi-modding** [comment]
Hello @DuckinBoots,
Yes it should work like this. Could you please share your log to see if I can see something wrong?

**Comment by DuckinBoots** [comment]
[log.txt](https://github.com/yumi-modding/FS22_CombineXP/files/8788806/log.txt)

**Comment by yumi-modding** [comment]
Hello
I don't see the line in the log  like Combine basePerf computed for RSM 161... meaning the basePerf is not computed and so might be retrieved from xml config file.
I guess the issue is more you are harvesting early in the morning and so the mod try to prevent you to simulate high moisture.
You can either try to harvest later (from 10am or 11am) or set

 `timeDependantSpeed isActive="false"`

**Comment by DuckinBoots** [comment]
I think  that problem is solved. I change xml in modsSettings  and it help. Thanks for help.

**Comment by yumi-modding** [comment]
Perfect
