### ISSUE TITLE
Question: combine load

### ISSUE THREAD

**Issue by Fracking** [yumi-modding/FS22_CombineXP#38]
Hey Yumi,
just a general question: Does this mod change the actual load on the combine? The reason I ask is because engine load of the combine stays at 60-70% (LoadHUD mod, not the CombineXP HUD. Fuel usage is also pretty much the same). The CombineXP HUD shows a load of 90-110% but these loads don´t sync (90% ≠ 60% / 110% ≠ 70%). I guess the CombineXP "load" is the general threshing load (not necessarily the engine load). However, I´d like to see the CombineXP load somehow passed to the game engine. Right now, when I turn on the combine, the engine load hovers randomly between 60% and 70% even if its not really threshing, so it might also be a FS2022 thing.

I hope you get my point :)
Keep up the great work.

Fracking

**Comment by yumi-modding** [comment]
Hello @Fracking 
You're right, the mod does not change the combine engine load and the load display in the hud is kind of threshing load.
As you might know already, the mod compute the load and then finally just impacts the getSpeedLimit function because as per Giants code, without speed limit on combine, you could actually harvest at combine max speed with any header, provided you get enough engine power to start the header (most engine load or maybe all comes from header in Giants computation cf. #28 )
I remember on More Realistic mod (computation is based on this mod) there was also a notion of engine load for combine and I guess it can be notice as reducing speed when threshing capacity is high and combine is climbing a slope. Also impact on fuel consumption would be possible with this.
The thing with this mod was that you needed to define every required power:  
- threshing required power base + depending on material quantity 
- chopper required power 
- header required power base + depending on material quantity
- unloading required power
This open a lot of capabilities but either I would need to set default values or set all this for every harvester/header in game.

**Comment by Fracking** [comment]
Thank you for your answer.

I remember the More Realistic mod. That was great fun. Not perfect, but definitly better than stock. It´s always sad to see that Giants go more an approximative way of load calculation. Like, "that tool should us x kW during work", but the current speed and crop density is basicly ignored...

It would be alot of work for a single person to integrate this, but I would like to see Giants do more of these calculations (it can be done. Like gearboxes). I guess these things/details don´t sell as well as adding 100 new machines that basicly feel the same...

Oh well... Thank you for your effort.
